"""Deterministic, credential-free end-to-end demonstration bundle."""

from __future__ import annotations

import json
import shutil
import subprocess
from datetime import UTC, datetime
from enum import StrEnum
from pathlib import Path
from typing import Any

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas

from proceedings_to_eee.corpus import PaperSpec
from proceedings_to_eee.domain.status import ActorRole, EvidenceKind
from proceedings_to_eee.extraction.llm import EXTRACTOR_SCHEMA_NAME
from proceedings_to_eee.extraction.pdf_layout import extract_pdf_layout
from proceedings_to_eee.io import (
    atomic_write_bytes,
    read_json,
    sha256_bytes,
    sha256_file,
    write_json,
    write_jsonl,
)
from proceedings_to_eee.pipeline import PipelineSettings, run_paper
from proceedings_to_eee.providers.openrouter import (
    ProviderCall,
    StructuredResponse,
    completion_token_parameter_for_model,
    structured_request_contract,
)
from proceedings_to_eee.resources import DEFAULT_EEE_SCHEMA_PATH, EEE_SCHEMA_SHA256
from proceedings_to_eee.reviewed_export.models import (
    DecisionAuthority,
    DecisionStatus,
    OriginDecision,
    ReviewAuthorityMode,
    ReviewedExportDecision,
    ReviewEvidenceAnchor,
    ReviewFieldAttestation,
    ReviewItem,
    ReviewManifest,
    TupleDecision,
    model_payload,
)
from proceedings_to_eee.reviewed_export.workflow import (
    REVIEW_DECISIONS_NAME,
    REVIEW_ITEMS_NAME,
    REVIEW_MANIFEST_NAME,
    compose_reviewed_eee,
    prepare_export_review,
    validate_export_review,
    verify_derived_run,
)
from proceedings_to_eee.run_seal import seal_run_tree, verify_run_seal
from proceedings_to_eee.sources.manifest import (
    LicenseDisposition,
    SourceManifest,
    SourceRole,
    freeze_local_source,
)

DEMO_SCHEMA_VERSION = "offline-demo-bundle/0.1"
DEMO_PAPER_ID = "synthetic-demo-paper"
DEMO_TITLE = "A Synthetic Evaluation for Proceedings-to-EEE"
DEMO_MODEL = "offline-fixture/deterministic-v1"
DEMO_REVIEWER_ID = "synthetic-demo-attestation"
DEMO_DECIDED_AT = datetime(2026, 1, 1, tzinfo=UTC)
DEMO_PDF_NAME = "synthetic-paper.pdf"
DEMO_MANIFEST_NAME = "demo-manifest.json"
DEMO_SHA256SUMS_NAME = "SHA256SUMS"
DEMO_LICENSE_NAME = "SYNTHETIC-SOURCE-LICENSE.txt"

DEMONET_ORIGIN_TEXT = "Our team trained DemoNet and evaluated DemoNet on DemoSet in this study."
EXTERNAL_ORIGIN_TEXT = (
    "The ExternalBaseline result is reproduced from Smith et al. (2024); "
    "we did not run ExternalBaseline."
)

_LICENSE_TEXT = """Synthetic source license

The synthetic paper generated by `ere demo` contains no third-party paper text or data.
It is dedicated to the public domain under CC0-1.0 and may be copied, modified, and
redistributed without restriction. The software remains covered by the repository license.
"""


class OfflineDemoErrorCode(StrEnum):
    OUTPUT_EXISTS = "OUTPUT_EXISTS"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    FIXTURE_CONTRACT_FAILED = "FIXTURE_CONTRACT_FAILED"
    DEMO_ASSERTION_FAILED = "DEMO_ASSERTION_FAILED"


class OfflineDemoError(RuntimeError):
    """Stable, path-free demo failure suitable for command-line output."""

    def __init__(self, code: OfflineDemoErrorCode, detail: str) -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}")


def _demo_error(code: OfflineDemoErrorCode, detail: str) -> OfflineDemoError:
    return OfflineDemoError(code, detail)


def generate_demo_pdf(path: Path) -> str:
    """Generate the two-page redistributable source with path-independent bytes."""

    path.parent.mkdir(parents=True, exist_ok=True)
    document = canvas.Canvas(
        str(path),
        pagesize=LETTER,
        bottomup=1,
        pageCompression=0,
        invariant=1,
    )
    document.setTitle(DEMO_TITLE)
    document.setAuthor("Proceedings-to-EEE contributors")
    document.setCreator("ere demo deterministic fixture")
    document.setSubject("Redistributable CC0-1.0 synthetic evaluation paper")
    width, height = LETTER

    def page_frame(page_number: int, section: str) -> None:
        document.setFillColor(HexColor("#17365D"))
        document.rect(0, height - 54, width, 54, fill=1, stroke=0)
        document.setFillColor(HexColor("#FFFFFF"))
        document.setFont("Helvetica-Bold", 10)
        document.drawString(54, height - 33, "PROCEEDINGS-TO-EEE / SYNTHETIC DEMO")
        document.setFillColor(HexColor("#17365D"))
        document.setFont("Helvetica-Bold", 9)
        document.drawRightString(width - 54, 37, f"{section}  |  {page_number} of 2")
        document.setFont("Helvetica", 7.5)
        document.drawString(54, 37, "CC0-1.0 synthetic source - no real study or system")

    page_frame(1, "Methods")
    document.setFillColor(HexColor("#111827"))
    document.setFont("Helvetica-Bold", 20)
    document.drawString(54, height - 94, DEMO_TITLE)
    document.setFont("Helvetica", 10)
    document.setFillColor(HexColor("#475569"))
    document.drawString(54, height - 115, "A deterministic, redistributable pipeline fixture")
    document.setFillColor(HexColor("#111827"))
    document.setFont("Helvetica-Bold", 13)
    document.drawString(54, height - 166, "1. Methods")
    body = document.beginText(54, height - 193)
    body.setFont("Helvetica", 10.5)
    body.setLeading(18)
    body.textLine("DemoSet is a synthetic test set containing 100 invented examples.")
    body.textLine(DEMONET_ORIGIN_TEXT)
    body.textLine(EXTERNAL_ORIGIN_TEXT)
    body.textLine("Accuracy is the fraction of examples assigned the synthetic reference label.")
    document.drawText(body)
    document.setFillColor(HexColor("#E8F0F8"))
    document.roundRect(54, height - 340, width - 108, 72, 6, fill=1, stroke=0)
    document.setFillColor(HexColor("#17365D"))
    document.setFont("Helvetica-Bold", 10)
    document.drawString(68, height - 292, "Fixture scope")
    document.setFont("Helvetica", 9)
    document.drawString(68, height - 312, "All names, values, citations, and claims are fictional.")
    document.drawString(
        68, height - 328, "The document exists only to exercise the public pipeline."
    )
    document.showPage()

    page_frame(2, "Results")
    document.setFillColor(HexColor("#111827"))
    document.setFont("Helvetica-Bold", 18)
    document.drawString(54, height - 94, "2. Results")
    document.setFont("Helvetica", 10)
    document.setFillColor(HexColor("#475569"))
    document.drawString(
        54,
        height - 117,
        "The table mixes one result produced here with one cited result.",
    )
    document.setFillColor(HexColor("#111827"))
    document.setFont("Helvetica-Bold", 11)
    document.drawString(54, height - 163, "Table 1: Accuracy on DemoSet")
    table = document.beginText(66, height - 196)
    table.setFont("Courier-Bold", 10.5)
    table.setLeading(23)
    table.textLine("System                                      DemoSet Accuracy")
    table.setFont("Courier", 10.5)
    table.textLine("DemoNet                                     0.91")
    table.textLine("ExternalBaseline (Smith et al., 2024)       0.88")
    document.drawText(table)
    document.setStrokeColor(HexColor("#94A3B8"))
    document.setLineWidth(0.6)
    document.line(60, height - 206, width - 60, height - 206)
    document.line(60, height - 252, width - 60, height - 252)
    document.setFillColor(HexColor("#475569"))
    document.setFont("Helvetica-Oblique", 8.5)
    document.drawString(
        54,
        height - 288,
        "Note: ExternalBaseline is shown for comparison and was not run in this study.",
    )
    document.save()
    return sha256_file(path)


def _provider_observation(
    *, system: str, quote: str, context_quote: str, raw_value: str, numeric: float
) -> dict[str, Any]:
    return {
        "claim_type": "primary_result",
        "roles": [
            {
                "role": "evaluated_system",
                "raw_name": system,
                "version": None,
                "provider": None,
                "confidence": 1.0,
            }
        ],
        "scope": {
            "dataset_raw": "DemoSet",
            "dataset_id": None,
            "dataset_url": None,
            "dataset_version": None,
            "split": None,
            "subset": None,
            "group": None,
            "language": None,
            "sample_count": None,
            "aggregation": None,
            "raw_scope": None,
        },
        "metric": {
            "raw_name": "Accuracy",
            "canonical_id": "accuracy",
            "kind": "accuracy",
            "unit": "proportion",
            "lower_is_better": False,
            "min_score": 0.0,
            "max_score": 1.0,
            "parameters": {},
        },
        "value": {
            "raw": raw_value,
            "numeric": numeric,
            "unit": "proportion",
            "comparator": "exact",
            "uncertainty": None,
        },
        "evidence": [
            {
                "kind": "table",
                "label": "Table 1",
                "row": system,
                "column": "Accuracy",
                "quote": quote,
            },
            {
                "kind": "table",
                "label": "Table 1",
                "row": None,
                "column": "Accuracy",
                "quote": context_quote,
            },
        ],
        "extraction_confidence": 1.0,
        "construct": None,
        "operationalization": None,
        "decision_rule": None,
        "evaluation_date": None,
        "notes": ["deterministic offline demonstration fixture"],
    }


class _OfflineFixtureClient:
    """Return deterministic wire records through the normal structured-chat API."""

    def __init__(self) -> None:
        self.call_count = 0

    @staticmethod
    def _result_line(user: str, system: str, raw_value: str) -> str | None:
        for line in user.splitlines():
            stripped = line.strip()
            if stripped.startswith(system) and raw_value in stripped:
                return stripped
        return None

    @staticmethod
    def _table_header_line(user: str) -> str | None:
        for line in user.splitlines():
            stripped = line.strip()
            if stripped.startswith("System") and "DemoSet" in stripped and "Accuracy" in stripped:
                return stripped
        return None

    def structured_chat(self, **kwargs: Any) -> StructuredResponse:
        if kwargs.get("schema_name") != EXTRACTOR_SCHEMA_NAME:
            raise _demo_error(
                OfflineDemoErrorCode.FIXTURE_CONTRACT_FAILED,
                "offline fixture received an unsupported extraction schema",
            )
        self.call_count += 1
        user = kwargs["user"]
        observations: list[dict[str, Any]] = []
        context_quote = self._table_header_line(user)
        for system, raw_value, numeric in (
            ("DemoNet", "0.91", 0.91),
            ("ExternalBaseline", "0.88", 0.88),
        ):
            quote = self._result_line(user, system, raw_value)
            if quote is not None and context_quote is not None:
                observations.append(
                    _provider_observation(
                        system=system,
                        quote=quote,
                        context_quote=context_quote,
                        raw_value=raw_value,
                        numeric=numeric,
                    )
                )
        payload = {
            "observations": observations,
            "page_summary": "synthetic accuracy table",
            "warnings": [],
        }
        contract = structured_request_contract(
            schema_name=kwargs["schema_name"],
            schema=kwargs["schema"],
            seed=kwargs.get("seed"),
            require_parameters=kwargs.get("require_parameters", False),
        )
        prompt_bytes = json.dumps(
            [
                {"role": "system", "content": kwargs["system"]},
                {"role": "user", "content": kwargs["user"]},
            ],
            sort_keys=True,
            ensure_ascii=False,
        ).encode("utf-8")
        response_bytes = json.dumps(
            payload, sort_keys=True, ensure_ascii=False, separators=(",", ":")
        ).encode("utf-8")
        schema_contract = contract["schema"]
        return StructuredResponse(
            payload=payload,
            call=ProviderCall(
                model_requested=kwargs["model"],
                model_returned=kwargs["model"],
                provider_returned="offline-demo-fixture",
                prompt_sha256=sha256_bytes(prompt_bytes),
                response_sha256=sha256_bytes(response_bytes),
                temperature=kwargs["temperature"],
                reasoning_effort=kwargs["reasoning_effort"],
                max_tokens=kwargs["max_tokens"],
                completion_token_parameter=completion_token_parameter_for_model(kwargs["model"]),
                seed=contract["seed"],
                response_format=schema_contract["response_format"],
                schema_name=schema_contract["schema_name"],
                schema_sha256=schema_contract["schema_sha256"],
                schema_strict=schema_contract["schema_strict"],
                data_collection="deny",
                require_parameters=contract["routing"]["require_parameters"],
                zdr=True,
                latency_seconds=0.0,
                input_tokens=0,
                output_tokens=0,
                total_tokens=0,
                cost_usd=0.0,
                finish_reason="stop",
                attempts=1,
            ),
        )


def _jsonl_models(path: Path, model: type[Any]) -> list[Any]:
    records: list[Any] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        records.append(model.model_validate(json.loads(line)))
    return records


def _line_span(text: str, start: int, end: int) -> tuple[int, int]:
    return text.count("\n", 0, start) + 1, text.count("\n", 0, max(end - 1, 0)) + 1


def _origin_anchor(
    *,
    excerpt: str,
    manifest: ReviewManifest,
    review_root: Path,
) -> ReviewEvidenceAnchor:
    binding = manifest.papers[0]
    layout = read_json(review_root / binding.layout.review_copy.path)
    page = layout["pages"][0]
    page_text = page["text"]
    if page_text.count(excerpt) != 1:
        raise _demo_error(
            OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
            "synthetic origin evidence is not unique on its declared page",
        )
    start = page_text.index(excerpt)
    end = start + len(excerpt)
    start_line, end_line = _line_span(page_text, start, end)
    source_manifest = SourceManifest.model_validate(
        read_json(review_root / binding.source_manifest.review_copy.path)
    )
    source = next(
        source for source in source_manifest.sources if source.source_id == layout["source_id"]
    )
    assert source.sha256 is not None
    return ReviewEvidenceAnchor(
        source_id=source.source_id,
        source_sha256=source.sha256,
        source_manifest_sha256=binding.source_manifest.sha256,
        layout_sha256=binding.layout.sha256,
        parser=layout["parser"],
        parser_version=layout["parser_version"],
        page=1,
        page_text_sha256=page["text_sha256"],
        exact_excerpt=excerpt,
        excerpt_sha256=sha256_bytes(excerpt.encode("utf-8")),
        char_start=start,
        char_end=end,
        start_line=start_line,
        end_line=end_line,
        kind=EvidenceKind.PROSE,
        label="Methods",
    )


def _complete_demo_decisions(review_root: Path) -> None:
    manifest = ReviewManifest.model_validate(read_json(review_root / REVIEW_MANIFEST_NAME))
    items = _jsonl_models(review_root / REVIEW_ITEMS_NAME, ReviewItem)
    decisions = _jsonl_models(review_root / REVIEW_DECISIONS_NAME, ReviewedExportDecision)
    if len(items) != 2 or len(decisions) != 2:
        raise _demo_error(
            OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
            "synthetic extraction did not produce exactly two review items",
        )
    authority = DecisionAuthority(
        mode=ReviewAuthorityMode.SINGLE_EXPERT,
        reviewer_ids=[DEMO_REVIEWER_ID],
        protocol_sha256=manifest.protocol.sha256,
    )
    completed: list[ReviewedExportDecision] = []
    for item, decision in zip(items, decisions, strict=True):
        evaluated = [
            role.raw_name
            for role in item.candidate.roles
            if role.role is ActorRole.EVALUATED_SYSTEM
        ]
        if evaluated == ["DemoNet"]:
            origin = OriginDecision.PAPER_PRODUCED
            origin_text = DEMONET_ORIGIN_TEXT
        elif evaluated == ["ExternalBaseline"]:
            origin = OriginDecision.EXTERNALLY_SOURCED
            origin_text = EXTERNAL_ORIGIN_TEXT
        else:
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "synthetic review item has an unexpected evaluated system",
            )
        span_ids = sorted(
            str(anchor.span_id) for anchor in decision.result_evidence if anchor.span_id is not None
        )
        field_hashes = decision.reviewed_tuple.field_value_sha256s()
        field_attestations = [
            ReviewFieldAttestation(
                field=field,
                value_sha256=field_hashes[field],
                span_ids=span_ids,
            )
            for field in sorted(
                decision.reviewed_tuple.populated_fields(),
                key=lambda item: item.value,
            )
        ]
        payload = model_payload(decision)
        payload.update(
            {
                "status": DecisionStatus.COMPLETED.value,
                "tuple_decision": TupleDecision.CONFIRMED.value,
                "origin_decision": origin.value,
                "field_attestations": [
                    model_payload(attestation) for attestation in field_attestations
                ],
                "origin_evidence": [
                    model_payload(
                        _origin_anchor(
                            excerpt=origin_text,
                            manifest=manifest,
                            review_root=review_root,
                        )
                    )
                ],
                "authority": model_payload(authority),
                "decided_at": DEMO_DECIDED_AT.isoformat(),
                "notes": ["Fixed synthetic fixture attestation; not an empirical annotation."],
            }
        )
        completed.append(ReviewedExportDecision.model_validate(payload))
    write_jsonl(review_root / REVIEW_DECISIONS_NAME, completed)
    (review_root / REVIEW_DECISIONS_NAME).chmod(0o600)


def _root_inventory(root: Path) -> list[tuple[str, str]]:
    entries: list[tuple[str, str]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root).as_posix()
        if relative == DEMO_SHA256SUMS_NAME:
            continue
        if path.is_symlink() or (not path.is_file() and not path.is_dir()):
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "demo output contains an unsupported filesystem entry",
            )
        if path.is_file():
            entries.append((relative, sha256_file(path)))
    return entries


def _write_root_checksums(root: Path) -> str:
    content = "".join(f"{digest}  {path}\n" for path, digest in _root_inventory(root))
    atomic_write_bytes(root / DEMO_SHA256SUMS_NAME, content.encode("utf-8"))
    return sha256_file(root / DEMO_SHA256SUMS_NAME)


def verify_demo_bundle(root: Path) -> dict[str, Any]:
    """Verify the outer demo inventory and the independently checkable derived run."""

    sums_path = root / DEMO_SHA256SUMS_NAME
    if sums_path.is_symlink() or not sums_path.is_file():
        raise _demo_error(
            OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
            "demo checksum inventory is missing",
        )
    expected = "".join(f"{digest}  {path}\n" for path, digest in _root_inventory(root))
    if sums_path.read_text(encoding="utf-8") != expected:
        raise _demo_error(
            OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
            "demo checksum inventory does not match the output tree",
        )
    manifest = read_json(root / DEMO_MANIFEST_NAME)
    if not isinstance(manifest, dict) or manifest.get("schema_version") != DEMO_SCHEMA_VERSION:
        raise _demo_error(
            OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
            "demo audit manifest is invalid",
        )
    verified_seal = verify_run_seal(root / "sealed-run")
    derived = verify_derived_run(root / "derived")
    return {
        "status": "verified",
        "demo_manifest_sha256": sha256_file(root / DEMO_MANIFEST_NAME),
        "sha256s_sha256": sha256_file(sums_path),
        "source_run_seal_sha256": verified_seal.seal_sha256,
        "derived_run_sha256": derived.derived_run_sha256,
        "eee_record_count": derived.eee_record_count,
        "exported_observation_count": derived.exported_observation_count,
    }


def run_offline_demo(output_root: Path) -> dict[str, Any]:
    """Run the full local demonstration without credentials or network access."""

    output_root = output_root.resolve()
    if output_root.exists() or output_root.is_symlink():
        raise _demo_error(
            OfflineDemoErrorCode.OUTPUT_EXISTS,
            "demo output already exists; choose a new directory",
        )
    for binary in ("pdftotext", "pdfinfo"):
        if shutil.which(binary) is None:
            raise _demo_error(
                OfflineDemoErrorCode.DEPENDENCY_MISSING,
                "Poppler pdftotext and pdfinfo are required for the demo",
            )

    output_root.mkdir(parents=True)
    try:
        pdf_path = output_root / DEMO_PDF_NAME
        pdf_sha256 = generate_demo_pdf(pdf_path)
        pdf_info = subprocess.run(
            ["pdfinfo", str(pdf_path)],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        ).stdout
        if "Pages:           2" not in pdf_info:
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "synthetic PDF does not contain exactly two pages",
            )
        preview_layout = extract_pdf_layout(pdf_path, "synthetic-preview")
        if (
            preview_layout.page_count != 2
            or DEMONET_ORIGIN_TEXT not in preview_layout.pages[0].text
            or EXTERNAL_ORIGIN_TEXT not in preview_layout.pages[0].text
        ):
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "synthetic PDF text did not round-trip through production parsing",
            )
        atomic_write_bytes(output_root / DEMO_LICENSE_NAME, _LICENSE_TEXT.encode("utf-8"))

        work_root = output_root / "work-run"
        paper_work_root = work_root / DEMO_PAPER_ID
        source = freeze_local_source(
            paper_id=DEMO_PAPER_ID,
            role=SourceRole.PAPER,
            path=pdf_path,
            cache_root=output_root / "data" / "sources",
            original_uri=DEMO_PDF_NAME,
            license_disposition=LicenseDisposition.REDISTRIBUTABLE,
        ).model_copy(
            update={
                "retrieved_at": DEMO_DECIDED_AT,
                "resolved_uri": None,
                "notes": ["CC0-1.0 synthetic demonstration source"],
            }
        )
        source_manifest = SourceManifest(
            paper_id=DEMO_PAPER_ID,
            title=DEMO_TITLE,
            sources=[source],
        )
        write_json(paper_work_root / "source-manifest.json", source_manifest)
        spec = PaperSpec(
            paper_id=DEMO_PAPER_ID,
            title=DEMO_TITLE,
            year=2026,
            venue="Synthetic Proceedings",
            pdf_path=DEMO_PDF_NAME,
            perspective_role="evaluated_system",
            include_pages=[2],
            notes=["Redistributable offline demonstration fixture."],
        )
        settings = PipelineSettings(
            project_root=output_root,
            schema_path=DEFAULT_EEE_SCHEMA_PATH,
            schema_sha256=EEE_SCHEMA_SHA256,
            output_root=work_root,
            model=DEMO_MODEL,
            min_confidence=0.8,
            seed=7,
        )
        client = _OfflineFixtureClient()
        run = run_paper(spec=spec, settings=settings, client=client)
        # Runtime latency is useful telemetry in a real run but is not part of the
        # synthetic fixture's meaning. Canonicalize it before sealing so two demo
        # executions produce the same auditable bytes rather than merely the same
        # observations.
        run["wall_clock_seconds"] = 0.0
        write_json(paper_work_root / "run.json", run)
        if run["counts"]["candidates"] != 2 or run["counts"]["eee_records"] != 0:
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "unreviewed synthetic run did not preserve the expected export gate",
            )

        sealed_root = output_root / "sealed-run"
        seal_run_tree(paper_work_root, sealed_root)
        review_root = output_root / "review"
        review_manifest = prepare_export_review(
            run_root=sealed_root,
            output_root=review_root,
            min_confidence=0.8,
        )
        _complete_demo_decisions(review_root)
        review_lock, review_lock_sha = validate_export_review(review_root)
        derived_root = output_root / "derived"
        derived_manifest = compose_reviewed_eee(
            run_root=sealed_root,
            decisions_path=review_root / REVIEW_DECISIONS_NAME,
            output_root=derived_root,
        )
        verification = verify_derived_run(derived_root)
        if derived_manifest.counts != {
            "review_items": 2,
            "decisions_completed": 2,
            "decisions_pending": 0,
            "outcomes_exported": 1,
            "outcomes_withheld": 1,
            "outcomes_failed": 0,
            "eee_records": 1,
            "eee_observations": 1,
        }:
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "reviewed synthetic output does not have the expected outcome partition",
            )
        outcomes = [
            json.loads(line)
            for line in (derived_root / "export-outcomes.jsonl").read_text().splitlines()
        ]
        if (
            sum(
                outcome["state"] == "withheld" and outcome["failure_codes"] == ["ORIGIN_EXTERNAL"]
                for outcome in outcomes
            )
            != 1
        ):
            raise _demo_error(
                OfflineDemoErrorCode.DEMO_ASSERTION_FAILED,
                "external synthetic result was not withheld for the expected reason",
            )

        shutil.rmtree(work_root)
        audit = {
            "schema_version": DEMO_SCHEMA_VERSION,
            "status": "verified",
            "purpose": "Credential-free synthetic end-to-end demonstration; not a quality claim.",
            "network_used": False,
            "credentials_required": False,
            "synthetic_fixture": True,
            "empirical_annotation": False,
            "source": {
                "path": DEMO_PDF_NAME,
                "sha256": pdf_sha256,
                "pages": 2,
                "license": "CC0-1.0",
                "license_path": DEMO_LICENSE_NAME,
            },
            "pipeline": {
                "fixture_model": DEMO_MODEL,
                "structured_extraction_calls": client.call_count,
                "normal_extraction_api": True,
                "stages": [
                    "pdf_generation",
                    "poppler_layout_extraction",
                    "content_addressed_source_freeze",
                    "structured_candidate_extraction",
                    "candidate_validation",
                    "review_html",
                    "run_sealing",
                    "immutable_review_preparation",
                    "synthetic_fixture_attestation",
                    "review_locking",
                    "reviewed_eee_composition",
                    "derived_run_verification",
                ],
            },
            "artifacts": {
                "sealed_run": "sealed-run",
                "review_html": "sealed-run/review.html",
                "private_review": "review",
                "derived_run": "derived",
                "verification": "derived/verification.json",
            },
            "bindings": {
                "source_run_seal_sha256": review_manifest.run_seal.seal_sha256,
                "review_lock_sha256": review_lock_sha,
                "review_decisions_sha256": review_lock.decisions_sha256,
                "derived_payload_tree_sha256": derived_manifest.payload_tree_sha256,
                "derived_verification_sha256": sha256_file(derived_root / "verification.json"),
            },
            "counts": {
                "candidates": 2,
                "unreviewed_eee_records": 0,
                **derived_manifest.counts,
                "verified_eee_records": verification.eee_record_count,
            },
        }
        write_json(output_root / DEMO_MANIFEST_NAME, audit)
        _write_root_checksums(output_root)
        verified = verify_demo_bundle(output_root)
        return {
            "status": "verified-offline-demo",
            "output": str(output_root),
            "paper": str(pdf_path),
            "review_html": str(output_root / "sealed-run" / "review.html"),
            "derived_run": str(derived_root),
            "manifest": str(output_root / DEMO_MANIFEST_NAME),
            "sha256s": str(output_root / DEMO_SHA256SUMS_NAME),
            "counts": derived_manifest.counts,
            "verification": verified,
        }
    except BaseException:
        shutil.rmtree(output_root, ignore_errors=True)
        raise


__all__ = [
    "DEMO_MANIFEST_NAME",
    "DEMO_PDF_NAME",
    "DEMO_SCHEMA_VERSION",
    "DEMO_SHA256SUMS_NAME",
    "OfflineDemoError",
    "generate_demo_pdf",
    "run_offline_demo",
    "verify_demo_bundle",
]
